name: Automated Snapshot Sync
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ secrets.GH_EMAIL }}"  

      - name: Verify Changes
        run: |
          git status

      - name: Commit Changes if Needed
        run: |
          git add .
          git commit -m "Automated snapshot sync" || echo "No changes to commit"

      - name: Push Changes to GitHub
        run: |
          git push origin ${{ github.ref_name }} || echo "No changes to push"
